### ISSUE TITLE
wallet balance check doesn't work

### ISSUE THREAD

**Issue by gremsee** [alvinsga/candy-machine-v2#30]
![caf7cc7a-e211-4553-8ec7-6c294bde9c84](https://user-images.githubusercontent.com/97235050/151219538-1a6f3fd9-26df-4cfa-8156-4f484514a81c.jpg)

There is a balance of 0.19sol. 0.1sol are needed to mint one. If I increase the balance to 0,5sol it works
Whitelisteprice 0.1 public price 0.5

**Comment by alvinsga** [comment]
Thats odd, I haven't been able to replicate. Are you using the same RPC cluster on Phantom?

**Comment by Web3Pro90** [comment]
I am having the same issue. Can you help?

**Comment by gremsee** [comment]
> Thats odd, I haven't been able to replicate. Are you using the same RPC cluster on Phantom?

No. Used a custom RPC from quicknode and tried it with the normal mainnet RPC. 
What can I provide to help you?

**Comment by Web3Pro90** [comment]
Were you able to resolve the issue?

**Comment by gremsee** [comment]
not tried. used another frontend, but this is my favorite ... will try again in some days, maybe update solved it

**Comment by Web3Pro90** [comment]
Well the current update still has the issue. My whitelist price is 0.25 but people could not mint even with 0.33 in their wallet. It said insufficient funds but when they had much more like 0.5 or something they could mint and it charged 0.25 only. So the bug is still there. @alvinsga Can you help? If you need anything I can share it with you. I am currently using a different front end but if you want to test I can put this one up. Let me know. I used the UI on the mainnet BTW.

**Comment by alvinsga** [comment]
@gremsee @Web3Pro90 Apologies for the delay. I have released a fix for this issue in the latest commit, let me know if this resolves your issues.

**Comment by Web3Pro90** [comment]
@alvinsga Thx mate. The issue appears to be resolved. I tested with 0.27 SOL and it went through. thanks again.
